# Generated by Django 6.0.2 on 2026-02-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح کوتاه'),
        ),
    ]
